---
title: " "
output:
  html_document:
    toc_float: false
    css: css/style.css
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE )
root <- rprojroot::find_rstudio_root_file()
dataDir <- file.path(root, 'data')
shapeDir <- file.path(root, 'shape')
library(googlesheets4)
library(dplyr)
library(sf)
library(stringr)
library(lubridate)
library(leaflet)
library(shiny)
```

<br>
<div class="videoContainer">
   <div class="overlay">
   <div class="overlay-text">
   <h1> APN Sustainable Cities Research</h2>
<h4>Tracking Influences of Asian Urban GHG emissions for Sustainability Policies: Identifying Low Carbon Pathways to meet the Paris Agreement</h5>
</div>
</div>
<video autoplay muted loop>
  <source src="images/index_assets/mining.webm" type="video/webm">
Your browser does not support the video tag.
</video>
</div>

```{r}
br()
h3("About the Grant", style = "text-align:center")
p(class = "blurb",
"Over the past decades, Asia has undergone rapid urbanization.  This transformation has accompanied increased energy demand and subsequent greenhouse gas (GHG) emissions.  From 1990 to 2010, the number of urban residents in Asia grew by over 800 million, increasing the Asian share of global urban population from 45 to 52% while Asian CO2 emissions increased from 6 Gt to 14 Gt, increasing its share of global GHG emissions from 39 to 54%.  Further urbanization portends even higher emission levels.  The recent Paris Agreement (2015) has drawn attention to the dramatic actions necessary to keep emissions low and therefore climate stable.  Organizations such as UN-HABITAT & UNESCAP (through the creation of the Northeast Asia Low Carbon Cities platform) and Asian governments are moving to develop low carbon cities.  Application of mitigation policy for low carbon societies is complicated, however, by the unique regional development conditions (socially, physically, economically and politically).  Policies appropriate elsewhere may not work in the Asian context making it necessary to understand the historical dynamics associated with regional urban development, energy use and GHG emissions.  To address this challenge, we propose urban case study historical analyses of emissions and their driving forces in Asian cities.")  

```

```{r}
# 5472px x 400px for image size
br()
div(class="image-overlay",
img(src = "images/index_assets/index_break.png")
)
br()
```

```{r}
br()
h3("About the ISC", style = "text-align:center")
p(class = "blurb",
"The Institute for Sustainable Cities at Hunter College emerged from the ideas and goals of Ted Kheel, labor lawyer and nature enthusiast, to enhance New Yorker’s understanding and appreciation for sustainability.  William D. Solecki was the first Director, who in 2015, returned to his full-time position in the Department of Geography.  Peter J. Marcotullio has been the Director since that time.  The Institute serves a CUNY-wide audience of scholars, students and staff as well as performs research and outreach to local community and government offices.")
br()
p(class = "blurb",
"The Institute for Sustainable Cities at Hunter College (ISC) works to realize cities as part of the solution to sustainability challenges.  By developing innovative science of sustainability research projects, student and public programming events, engagement activities and new curriculum  we promote awareness of opportunities available to urban residents for proactive responses to on-going environmental change.  The institutes ultimate goal is to help generate a new generation of environmental thinkers at Hunter College and within the wider CUNY community that are committed to progressive urban change.  This goal is based on knowledge and understanding of sustainability science, local community needs, decision maker constraints and institutional context.  We promote these goals through four different programmatic areas: Urban Forests, Urban Water, Urban Growth, Energy and Climate Change and Urban Resilience.  
")  
```

```{r}
# 5472px x 400px for image size
br()
div(class="image-overlay",
img(src = "images/index_assets/index_break.png")
)
br()
```

```{r}
h3("About the APN", style = "text-align:center")
p(class = "blurb",
a("(APN )", "https://www.apn-gcr.org") ,
"is an intergovernmental network of 22 countries working towards an 
Asia-Pacific region that is successfully addressing the challenges of global change and sustainability. 
The mission of APN is to enable investigations of changes in the Earth’s life support systems and their 
implications for sustainable development in the Asia-Pacific region through support for research and science-based response 
strategies and measures, effective linkages between science and policy, and scientific capacity development. ")  
```


```{r}
mainDF <- read_sheet("https://docs.google.com/spreadsheets/d/1kcZ6gZW1_okGLb1QscCwcjCAi4W3osO18D-uceZcJME/edit?usp=sharing",sheet = 1)
```

```{r}
h3("Map of Research Locations")
```


```{r}
APNIcon <- makeIcon(
  iconUrl = "images/APN-logo-1-300x103.png",
  iconWidth = 50, iconHeight = 20,
  iconAnchorX = 0, iconAnchorY = 0
)
APNpopup <- paste0(  "<b><a href='https://www.apn-gcr.org/'>APN Homepage</a></b>")
```

```{r, fig.align='center'}
mainMapDF <- mainDF %>% 
    filter(Role == "Researcher") %>% 
    group_by(City, Country) %>% 
    summarize(Lat = first(Lat),
              Lon = first(Lon)) %>% 
    st_as_sf(coords = c("Lon", "Lat"), crs = 4326)

popup <- paste0( "Country: "
                 , mainMapDF$Country 
                 , "<br>"
                 , "City: "
                 , mainMapDF$City
                 , "<br>",
                 "<b><a href='",
                 paste0(stringr::str_to_lower(mainMapDF$City),".html"),
                 "'>Research Page</a></b>"
               )

leaflet(mainMapDF) %>%
  addProviderTiles(providers$Esri.WorldImagery) %>%
  addMarkers(popup = ~popup) %>%
  addMarkers(lat = 34.69838, lng = 135.215418, icon = APNIcon,
             popup = APNpopup)

```


