---
title: "About the Team"
output:
  html_document:
    toc_float: false
---

<!-- this is the lightbox popup js -->
<link href="//cdn.rawgit.com/noelboss/featherlight/1.3.2/release/featherlight.min.css" type="text/css" rel="stylesheet" title="Featherlight Styles" /><script src="//cdn.rawgit.com/noelboss/featherlight/1.3.2/release/featherlight.min.js" type="text/javascript" charset="utf-8"></script>

```{r setup, include=FALSE}
##setting code chunks for rest of sections no code being shown, and no messages.
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE )
```

Create summary of researchers associated with the grant. Who was funding the project, where the
researchers are based, and how they are connected with each other. Is there a singular 
mission or research interest that ties their work together. How is it culminating together
to answer the questions the grant is hoping to answer?

***

```{r}
## read in libraries
source("libraries.R")
## read in file helperFunctions.R for extra functions
source("helperFunctions.R")
## read in data
source("data.R")
# pipe in cities to get member bios per city
cities %>% map(~cityEach(.x, researchersDF)) %>% tagList()
```
