---
title: "Publications"
output:
  html_document:
    toc_float: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE )
library(htmltools)
source("helperFunctions.R")
```

```{r}
div(class="band full",
    pubType("Journals", "These are published articles",
            paperInfo("https://www.researchgate.net/publication/350165154_Corrigendum_to_The_future_urban_heat-wave_challenge_in_Africa_Exploratory_analysis_Global_Environ_Change_66_2021_102190", 
                      "https://res-1.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_170,w_170,f_auto,b_white,q_auto:eco/v1470150968/halqcskldv3ge9nkpjsq.png",
                      "Corrigendum to “The future urban heat-wave challenge in Africa: Exploratory analysis",
                      "Peter J. Marcotullio, Casten Kesler", 
                      "Urbanization and climate change are among the most important global trends affecting human well-being during the twenty-first century. One region expected to undergo enormous urbanization and be significantly affected by climate change is Africa. Studies already find increases in temperature and high temperature events for the region." ),
            paperInfo("https://www.sciencedirect.com/science/article/abs/pii/S0169204602001524", 
                      "https://ars.els-cdn.com/content/image/1-s2.0-S0169204621X00023-cov150h.gif",
                      "Materials flow analysis and emergy evaluation of Taipei’s urban constructio",
                      "Shu-LiHuang, Wan-LinHsu", 
                      "The metabolism of a city can be seen as the process of transforming all the materials and commodities for sustaining the city’s economic activity. This paper attempts to incorporate resource and material flow analysis to investigate Taipei area’s urban sustainability due to urban construction. ." )
))
```

